{{- if .Values.exchange.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenuo-github-actions.exchangeServiceAccountName" . }}
  labels:
    {{- include "tenuo-github-actions.labels" . | nindent 4 }}
    app.kubernetes.io/component: exchange
  {{- with .Values.exchange.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.exchange.serviceAccount.automount }}
{{- end }}
