"""Python half of the cross-language PoP canonicalization fixture test.

Reads the shared fixture at
``tenuo-core/tests/fixtures/pop_canonical.json`` and asserts that
:meth:`Warrant.sign` produces the exact byte sequence the fixture
records for every case. A sibling test in Rust
(``tenuo-core/tests/pop_canonical_fixture.rs``) asserts the same thing
against the same fixture — any canonicalization drift between Python and
Rust will fail one of the two tests.

The fixture is regenerated by
``tenuo-python/tests/unit/_regen_pop_canonical.py``. Do not modify the
JSON by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tenuo._pop_canonicalize import strip_none_values
from tenuo_core import SigningKey, Warrant


FIXTURE_PATH = (
    Path(__file__).resolve().parents[3]
    / "tenuo-core"
    / "tests"
    / "fixtures"
    / "pop_canonical.json"
)


@pytest.fixture(scope="module")
def fixture_data():
    if not FIXTURE_PATH.exists():
        pytest.skip(f"fixture not present at {FIXTURE_PATH}")
    with FIXTURE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def test_fixture_is_well_formed(fixture_data):
    assert fixture_data["version"] == 1
    assert len(fixture_data["cases"]) >= 1
    for case in fixture_data["cases"]:
        for key in ("name", "tool", "args", "warrant_b64", "timestamp", "expected_signature_hex"):
            assert key in case, f"case {case.get('name')!r} missing key {key}"
        assert len(bytes.fromhex(case["expected_signature_hex"])) == 64
        if "raw_args" in case:
            assert strip_none_values(case["raw_args"]) == case["args"]


def test_python_pop_matches_fixture(fixture_data):
    """The Python ``Warrant.sign`` path must produce byte-identical
    signatures to what the fixture committed, for every case. Any change
    to the canonicalization on the Python side — or to the Rust core
    underneath it — will break this test.
    """
    holder_priv = bytes.fromhex(fixture_data["holder_priv_hex"])
    holder = SigningKey.from_bytes(holder_priv)

    failures = []
    for case in fixture_data["cases"]:
        warrant = Warrant.from_base64(case["warrant_b64"])
        sig_bytes = bytes(
            warrant.sign(holder, case["tool"], case["args"], case["timestamp"])
        )
        expected = bytes.fromhex(case["expected_signature_hex"])
        if sig_bytes != expected:
            failures.append(
                (case["name"], expected.hex(), sig_bytes.hex())
            )

    assert not failures, (
        "PoP canonicalization drift — cases that did not reproduce:\n"
        + "\n".join(
            f"  {name}:\n    expected {exp}\n    got      {got}"
            for name, exp, got in failures
        )
    )
